package com.example.kafkallmagent.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Objects;

/**
 * Structured enrichment generated by the LLM for one ticket.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record TicketEnrichment(
        String category,
        String priority,
        String sentiment,
        String routingQueue,
        String shortSummary,
        String suggestedReply,
        double confidence
) {

    /**
     * Validates the structured output returned by the language model before it is published to
     * Kafka. The checks enforce the minimum contract expected by downstream consumers of the
     * enriched event.
     */
    public TicketEnrichment {
        category = requireText(category, "category");
        priority = requireText(priority, "priority");
        sentiment = requireText(sentiment, "sentiment");
        routingQueue = requireText(routingQueue, "routingQueue");
        shortSummary = requireText(shortSummary, "shortSummary");
        suggestedReply = requireText(suggestedReply, "suggestedReply");
        if (confidence < 0.0 || confidence > 1.0) {
            throw new IllegalArgumentException("confidence must be between 0.0 and 1.0");
        }
    }

    private static String requireText(String value, String fieldName) {
        Objects.requireNonNull(value, fieldName);
        String trimmed = value.trim();
        if (trimmed.isEmpty()) {
            throw new IllegalArgumentException(fieldName + " must not be blank");
        }
        return trimmed;
    }
}
