package com.example.kafkallmagent.business;

import com.example.kafkallmagent.llm.LanguageModelClient;
import com.example.kafkallmagent.model.SupportTicketEvent;
import com.example.kafkallmagent.model.TicketEnrichment;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Objects;
import java.util.logging.Logger;

/**
 * Calls the language model and parses a structured enrichment object.
 */
public final class TicketEnrichmentService {

    private static final Logger LOGGER = Logger.getLogger(TicketEnrichmentService.class.getName());
    private static final int MAX_PARSE_ATTEMPTS = 2;

    private final TicketPromptFactory promptFactory;
    private final LanguageModelClient languageModelClient;
    private final ObjectMapper objectMapper;

    /**
     * Creates the enrichment service using the default Jackson mapper for structured JSON parsing.
     * This is the constructor used by production code in the PoC.
     *
     * @param promptFactory component that turns a support ticket into a strict model prompt
     * @param languageModelClient boundary used to call the underlying LLM provider
     */
    public TicketEnrichmentService(TicketPromptFactory promptFactory, LanguageModelClient languageModelClient) {
        this(promptFactory, languageModelClient, new ObjectMapper());
    }

    TicketEnrichmentService(
            TicketPromptFactory promptFactory,
            LanguageModelClient languageModelClient,
            ObjectMapper objectMapper
    ) {
        this.promptFactory = Objects.requireNonNull(promptFactory, "promptFactory");
        this.languageModelClient = Objects.requireNonNull(languageModelClient, "languageModelClient");
        this.objectMapper = Objects.requireNonNull(objectMapper, "objectMapper");
    }

    /**
     * Enriches a raw support ticket by asking the model for a structured JSON response and parsing
     * that response into the domain record used by the Kafka pipeline. If the first response cannot
     * be parsed, the method performs lightweight JSON repair and then retries once with stricter
     * output instructions.
     *
     * @param ticket raw support-ticket event that needs classification and routing metadata
     * @return structured enrichment generated by the model
     * @throws IllegalArgumentException if the model response cannot be turned into valid
     *                                  {@link TicketEnrichment} after all parse attempts
     */
    public TicketEnrichment enrich(SupportTicketEvent ticket) {
        Objects.requireNonNull(ticket, "ticket");
        LOGGER.info(() -> "Classifying support ticket '%s' with Ollama. Subject: %s"
                .formatted(ticket.ticketId(), ticket.subject()));

        String basePrompt = promptFactory.buildPrompt(ticket);
        String lastSanitizedResponse = "";
        JsonProcessingException lastException = null;

        for (int attempt = 1; attempt <= MAX_PARSE_ATTEMPTS; attempt++) {
            String prompt = attempt == 1
                    ? basePrompt
                    : buildRepairPrompt(basePrompt, lastSanitizedResponse);
            String modelResponse = languageModelClient.generate(prompt);
            String sanitizedResponse = repairJsonIfNeeded(sanitizeModelResponse(modelResponse));
            lastSanitizedResponse = sanitizedResponse;

            try {
                TicketEnrichment enrichment = objectMapper.readValue(sanitizedResponse, TicketEnrichment.class);
                LOGGER.info(() -> "Completed classification for ticket '%s'. Category='%s', Priority='%s', RoutingQueue='%s', Confidence=%.2f"
                        .formatted(
                                ticket.ticketId(),
                                enrichment.category(),
                                enrichment.priority(),
                                enrichment.routingQueue(),
                                enrichment.confidence()
                        ));
                return enrichment;
            } catch (JsonProcessingException exception) {
                lastException = exception;
                LOGGER.warning("Could not parse ticket enrichment JSON for ticket '%s' on attempt %d. Retrying with stricter JSON instructions."
                        .formatted(ticket.ticketId(), attempt));
            }
        }

        throw new IllegalArgumentException("Could not parse model response as TicketEnrichment: " + lastSanitizedResponse, lastException);
    }

    private static String buildRepairPrompt(String basePrompt, String invalidResponse) {
        return basePrompt + """

                
                Your previous response was not valid JSON.
                Return valid JSON only.
                Do not add markdown, comments, or extra text.
                Previous invalid response:
                """ + invalidResponse;
    }

    static String sanitizeModelResponse(String response) {
        Objects.requireNonNull(response, "response");
        String trimmed = response.trim();
        if (trimmed.startsWith("```")) {
            trimmed = trimmed.replaceFirst("^```[a-zA-Z0-9]*\\s*", "");
            trimmed = trimmed.replaceFirst("\\s*```$", "");
        }
        return trimmed.trim();
    }

    static String repairJsonIfNeeded(String response) {
        Objects.requireNonNull(response, "response");
        int openBraces = 0;
        int closeBraces = 0;
        int openBrackets = 0;
        int closeBrackets = 0;

        for (int index = 0; index < response.length(); index++) {
            char current = response.charAt(index);
            if (current == '{') {
                openBraces++;
            } else if (current == '}') {
                closeBraces++;
            } else if (current == '[') {
                openBrackets++;
            } else if (current == ']') {
                closeBrackets++;
            }
        }

        StringBuilder repaired = new StringBuilder(response);
        while (closeBrackets < openBrackets) {
            repaired.append(']');
            closeBrackets++;
        }
        while (closeBraces < openBraces) {
            repaired.append('}');
            closeBraces++;
        }

        return repaired.toString().trim();
    }
}
